
logging:
  level:
    root: info
    
server:
  port: 7000
  servlet:
    context-path: /api/v1
    
management:
  endpoints:
    web:
      exposure:
         include: info,health,env,metrics
      base-path: /management    
    
spring:
  
  jackson:
    deserialization:
      accept-single-value-as-array: true
    serialization:
      write-dates-as-timestamps: false
    generator:
      write-numbers-as-strings: true
    default-property-inclusion: NON_NULL
    date-format: yyyy-MM-dd'T'HH:mm:ssZ


---
spring.profiles: dev

logging:
  level:
    root: info
    com.me.work.greeting.api: debug

management:
  endpoints:
    web:
      exposure:
         include: health

   
---
spring.profiles: docker

logging:
  level:
    root: info
    com.me.work.greeting.api: debug

server:
  port: 8080
    
spring:
  data:
    mongodb:
      host: greeting-api-database
      port: 27017
      database: greetingsdb
      

---
spring.profiles: swagger

api:

  application-name: Greeting-api
  note: Greeting-api with contract first

  common:
    version: 1.0.0
    title: Greeting API
    description: The greeting-api is an example for the API implementation
    termsOfServiceUrl: MINE TERMS OF SERVICE URL
    license: License
    licenseUrl: MY LICENSE URL

    contact:
      name: Rudy SANIEZ
      url: https://github.com/rudysaniez
      email: rudysaniez@laposte.net
        